const requisitos = [];
// Micro E-mini Futures
requisitos.push({
    activo: 'Micro E-mini S&P 500',
    ticket: 'MES',
    ticketMT5: 'MES',
    market: 'Indices',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 1120, intradia: 40 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.25,
    valorTick: 1.25,
});  
requisitos.push({
    activo: 'Micro E-mini Nasdaq-100',
    ticket: 'MNQ',
    ticketMT5: 'MNQ',
    market: 'Indices',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 1680, intradia: 100 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.25,
    valorTick: 0.50,
});
requisitos.push({
    activo: 'Micro E-mini Dow',
    ticket: 'MYM',
    ticketMT5: 'MYM',
    market: 'Indices',
    contract: 'Microfuturos',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 800, intradia: 50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1.00,
    valorTick: 0.50,
    });
requisitos.push({
    activo: 'Micro E-mini Russell 2000',
    ticket: 'M2K',
    ticketMT5: 'M2K',
    market: 'Indices',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 620, intradia: 50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.10,
    valorTick: 0.50,
});  
requisitos.push({
    activo: 'Micro-DAX',
    ticket: 'FDXS',
    ticketMT5: 'FDXS',
    market: 'Indices',
    contract: 'Microfuturos',
    exchange: 'Eurex',
    margin: { mantenimiento: 1650, intradia: 100 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1.0,
    valorTick: 1.0,
});
requisitos.push({
    activo: 'Micro-EURO STOXX50',
    ticket: 'FSXE',
    ticketMT5: 'FSXE',
    market: 'Indices',
    contract: 'Microfuturos',
    exchange: 'Eurex',
    margin: { mantenimiento: 440, intradia: 50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.50,
    valorTick: 0.50,
});
// Stock Index
requisitos.push({
    activo: 'E-mini S&P 500',
    ticket: 'ES',
    ticketMT5: 'EP',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 11200, intradia: 400 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.25,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'E-mini Nasdaq-100',
    ticket: 'NQ',
    ticketMT5: 'ENQ',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 16800, intradia: 1000 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.25,
    valorTick: 5.00,
});
requisitos.push({
    activo: 'E-mini Dow ($5)',
    ticket: 'YM',
    ticketMT5: 'YM',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 8000, intradia: 500 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1.00,
    valorTick: 5.00,
});
requisitos.push({
    activo: 'E-mini Russell 2000',
    ticket: 'RTY',
    ticketMT5: 'RTY',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 6200, intradia: 500 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.10,
    valorTick: 5.00,
});
requisitos.push({
    activo: 'E-mini S&P MidCap 400',
    ticket: 'EMD',
    ticketMT5: 'EMD',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 13500, intradia: 3375 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.10,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'NIKKEI 225/USD',
    ticket: 'NKD',
    ticketMT5: 'NKD',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 7000, intradia: 1750 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 5.00,
    valorTick: 25.00,
});
requisitos.push({
    activo: 'DAX',
    ticket: 'FDAX',
    ticketMT5: 'DD',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 41000, intradia: 2500 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1.00,
    valorTick: 25.00,
});
requisitos.push({
    activo: 'Mini-DAX',
    ticket: 'FDXM',
    ticketMT5: 'FDXM',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 8230, intradia: 500 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1.00,
    valorTick: 5.00,
});
requisitos.push({
    activo: 'EURO STOXX 50',
    ticket: 'FESX',
    ticketMT5: 'DSX',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 4420, intradia: 250 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1.00,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'STOXX Europe 600',
    ticket: 'FXXP',
    ticketMT5: 'FXXP',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 2120, intradia: 530 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.10,
    valorTick: 5.00,
    });
requisitos.push({
    activo: 'EURO STOXX Banks',
    ticket: 'FESB',
    ticketMT5: 'ESB',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 660, intradia: 165 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.05,
    valorTick: 2.50,
});
requisitos.push({
    activo: 'VSTOXX',
    ticket: 'FVS',
    ticketMT5: 'FVS',
    market: 'Indices',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 670, intradia: 167.50 },
    months: ['see exch.'],
    medidaTick: 0.05,
    valorTick: 5.00,
});
// Currencies
requisitos.push({
    activo: 'Australian Dollar',
    ticket: '6A',
    ticketMT5: 'DA6',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 1800, intradia: 450 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'British Pound',
    ticket: '6B',
    ticketMT5: 'BP6',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 2800, intradia: 700 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 6.25,
});
requisitos.push({
    activo: 'Canadian Dollar',
    ticket: '6C',
    ticketMT5: 'CA6',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 1200, intradia: 300 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.00005,
    valorTick: 5.00,
}); 
requisitos.push({
    activo: 'Euro FX',
    ticket: '6E',
    ticketMT5: 'EU6',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 2650, intradia: 662 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.00005,
    valorTick: 6.25,
}); 
requisitos.push({
    activo: 'Japanese Yen',
    ticket: '6J',
    ticketMT5: 'JY6',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 3720, intradia: 930 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0000005,
    valorTick: 6.25,
}); 
requisitos.push({
    activo: 'New Zealand Dollar',
    ticket: '6N',
    ticketMT5: 'NE6',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 1800, intradia: 450 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.00005,
    valorTick: 10.00,
}); 
requisitos.push({
    activo: 'Swiss Franc',
    ticket: '6S',
    ticketMT5: 'SF6',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 4500, intradia: 1125 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 12.50,
}); 
requisitos.push({
    activo: 'E-mini Euro FX',
    ticket: 'E7',
    ticketMT5: 'EEU',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 1325, intradia: 331 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 6.25,
}); 
requisitos.push({
    activo: 'E-mini Japanese Yen',
    ticket: 'J7',
    ticketMT5: 'EJY',
    market: 'Divisas',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 1860, intradia: 465 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.000001,
    valorTick: 6.25,
}); 
requisitos.push({
    activo: 'Micro AUD/USD',
    ticket: 'M6A',
    ticketMT5: 'M6A',
    market: 'Divisas',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 180, intradia: 45 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 1.0,
}); 
requisitos.push({
    activo: 'Micro GBP/USD',
    ticket: 'M6B',
    ticketMT5: 'M6B',
    market: 'Divisas',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 280, intradia: 70 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 0.625,
}); 
requisitos.push({
    activo: 'Micro CAD/USD',
    ticket: 'MCD',
    ticketMT5: 'GMCD',
    market: 'Divisas',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 120, intradia: 30 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 1.0,
}); 
requisitos.push({
    activo: 'Micro EUR/USD',
    ticket: 'M6E',
    ticketMT5: 'M6E',
    market: 'Divisas',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 265, intradia: 66 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 1.25,
}); 
requisitos.push({
    activo: 'Micro JPY/USD',
    ticket: 'MJY',
    ticketMT5: 'MJY',
    market: 'Divisas',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 250, intradia: 62.50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.000001,
    valorTick: 1.25,
}); 
requisitos.push({
    activo: 'Micro CHF/USD',
    ticket: 'MSF',
    ticketMT5: 'MSF',
    market: 'Divisas',
    contract: 'Microfuturos',
    exchange: 'CME',
    margin: { mantenimiento: 450, intradia: 112.50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.0001,
    valorTick: 1.25,
});
// Energies
requisitos.push({
    activo: 'Crude Oil',
    ticket: 'CL',
    ticketMT5: 'CLE',
    market: 'Energias',
    contract: 'Futuros',
    exchange: 'NYMEX/CME',
    margin: { mantenimiento: 6000, intradia: 1500 },
    months: ['All'],
    medidaTick: 0.01,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'E-mini Crude Oil',
    ticket: 'QM',
    ticketMT5: 'NQM',
    market: 'Energias',
    contract: 'Futuros',
    exchange: 'NYMEX/CME',
    margin: { mantenimiento: 3000, intradia: 750 },
    months: ['All'],
    medidaTick: 0.025,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'Micro WTI Crude Oil',
    ticket: 'MCL',
    ticketMT5: 'MCLE',
    market: 'Energias',
    contract: 'Microfuturos',
    exchange: 'NYMEX/CME',
    margin: { mantenimiento: 600, intradia: 150 },
    months: ['All'],
    medidaTick: 0.01,
    valorTick: 1.00,
});
requisitos.push({
    activo: 'Natural Gas',
    ticket: 'NG',
    ticketMT5: 'NGE',
    market: 'Energias',
    contract: 'Futuros',
    exchange: 'NYMEX/CME',
    margin: { mantenimiento: 4500, intradia: 4500 },
    months: ['All'],
    medidaTick: 0.001,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'E-mini Natural Gas',
    ticket: 'QG',
    ticketMT5: 'NQG',
    market: 'Energias',
    contract: 'Futuros',
    exchange: 'NYMEX/CME',
    margin: { mantenimiento: 1125, intradia: 1125 },
    months: ['All'],
    medidaTick: 0.005,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'RBOB Gasoline',
    ticket: 'RB',
    ticketMT5: 'RBE',
    market: 'Energias',
    contract: 'Futuros',
    exchange: 'NYMEX/CME',
    margin: { mantenimiento: 7500, intradia: 7500 },
    months: ['All'],
    medidaTick: 0.0001,
    valorTick: 4.20,
});
requisitos.push({
    activo: 'Heating Oil',
    ticket: 'HO',
    ticketMT5: 'HOE',
    market: 'Energias',
    contract: 'Futuros',
    exchange: 'NYMEX/CME',
    margin: { mantenimiento: 9000, intradia: 9000 },
    months: ['All'],
    medidaTick: 0.0001,
    valorTick: 4.20,
});
// Metals
requisitos.push({
    activo: 'Gold',
    ticket: 'GC',
    ticketMT5: 'GCE',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 8000, intradia: 2000 },
    months: ['G', 'J', 'M', 'Q', 'V', 'Z'],
    medidaTick: 0.10,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'E-mini Gold',
    ticket: 'QO',
    ticketMT5: 'MQO',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 4000, intradia: 1000 },
    months: ['F', 'G', 'J', 'M', 'Q', 'V', 'Z'],
    medidaTick: 0.25,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'Micro Gold',
    ticket: 'MGC',
    ticketMT5: 'MGC',
    market: 'Metales',
    contract: 'Microfuturos',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 800, intradia: 200 },
    months: ['G', 'J', 'M', 'Q', 'V', 'Z'],
    medidaTick: 0.10,
    valorTick: 1.00,
});
requisitos.push({
    activo: 'Copper',
    ticket: 'HG',
    ticketMT5: 'CPE',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 6100, intradia: 1525 },
    months: ['All'],
    medidaTick: 0.0005,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'E-mini Copper',
    ticket: 'QC',
    ticketMT5: 'MQC',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 3050, intradia: 762.50 },
    months: ['All'],
    medidaTick: 0.002,
    valorTick: 25.00,
});
requisitos.push({
    activo: 'Silver',
    ticket: 'SI',
    ticketMT5: 'SIE',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 9500, intradia: 9500 },
    months: ['F', 'H', 'K', 'N', 'U', 'Z'],
    medidaTick: 0.005,
    valorTick: 25.00,
});
requisitos.push({
    activo: 'E-mini Silver',
    ticket: 'QI',
    ticketMT5: 'MQI',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 4750, intradia: 4750 },
    months: ['F', 'G', 'H', 'K', 'N', 'U', 'Z'],
    medidaTick: 0.0125,
    valorTick: 31.25,
});
requisitos.push({
    activo: 'E-micro Silver',
    ticket: 'SIL',
    ticketMT5: 'SIL',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 1900, intradia: 1900 },
    months: ['F', 'H', 'K', 'N', 'U', 'V', 'X', 'Z'],
    medidaTick: 0.01,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Platinum',
    ticket: 'PL',
    ticketMT5: 'PLE',
    market: 'Metales',
    contract: 'Futuros',
    exchange: 'COMEX/CME',
    margin: { mantenimiento: 3700, intradia: 3700 },
    months: ['F', 'J', 'N', 'V'],
    medidaTick: 0.1,
    valorTick: 5.00,
});
// Financials
requisitos.push({
    activo: 'Ultra U.S. Treasury Bond',
    ticket: 'UB',
    ticketMT5: 'ULA',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 6500, intradia: 1625 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/32,
    valorTick: 31.25,
});
requisitos.push({
    activo: 'Ultra 10-Year U.S. Treasury Note',
    ticket: 'TN',
    ticketMT5: 'TNA',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 3100, intradia: 775 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/32,
    valorTick: 15.625,
});
requisitos.push({
    activo: '3-Year U.S. Treasury Note',
    ticket: 'Z3N',
    ticketMT5: 'Z3N',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 1800, intradia: 450 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/128,
    valorTick: 15.625,
});
requisitos.push({
    activo: 'U.S. Treasury Bond',
    ticket: 'ZB',
    ticketMT5: 'USA',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 3800, intradia: 950 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/32,
    valorTick: 31.25,
});
requisitos.push({
    activo: 'Micro 30-Year Yield',
    ticket: '30YY',
    ticketMT5: 'Z30Y',
    market: 'Bonos',
    contract: 'Microfuturos',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 300, intradia: 75 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/10,
    valorTick: 1.00,
});
requisitos.push({
    activo: '5-Year U.S. Treasury Note',
    ticket: 'ZF',
    ticketMT5: 'FVA',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 1300, intradia: 325 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/128,
    valorTick: 7.8125,
});
requisitos.push({
    activo: 'Micro 5-Year Yield',
    ticket: '5YY',
    ticketMT5: 'Z5YY',
    market: 'Bonos',
    contract: 'Microfuturos',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 350, intradia: 87.50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/10,
    valorTick: 1.00,
});
requisitos.push({
    activo: '10-Year U.S. Treasury Note',
    ticket: 'ZN',
    ticketMT5: 'TYA',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 1950, intradia: 487.50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/64,
    valorTick: 15.625,
});
requisitos.push({
    activo: 'Micro 10-Year Yield',
    ticket: '10YY',
    ticketMT5: 'Z10Y',
    market: 'Bonos',
    contract: 'Microfuturos',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 325, intradia: 81.25 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/10,
    valorTick: 1.00,
});
requisitos.push({
    activo: '30-Day Federal Funds',
    ticket: 'ZQ',
    ticketMT5: 'ZQE',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 450, intradia: 450 },
    months: ['All'],
    medidaTick: 0.005,
    valorTick: 20.835,
});
requisitos.push({
    activo: '2-Year U.S. Treasury Note',
    ticket: 'ZT',
    ticketMT5: 'TUA',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 1000, intradia: 250 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/128,
    valorTick: 15.625,
});
requisitos.push({
    activo: 'Micro 2-Year Yield',
    ticket: '2YY',
    ticketMT5: 'Z2YY',
    market: 'Bonos',
    contract: 'Microfuturos',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 350, intradia: 87.50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 1/10,
    valorTick: 1.00,
});
requisitos.push({
    activo: 'Eurodollar',
    ticket: 'GE',
    ticketMT5: 'EDA',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 725, intradia: 725 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.01,
    valorTick: 25.00,
});
requisitos.push({
    activo: 'Euro-Bund',
    ticket: 'FGBL',
    ticketMT5: 'DB',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 4450, intradia: 1112.50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.01,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Euro-Bobl',
    ticket: 'FGBM',
    ticketMT5: 'DL',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 2785, intradia: 696.25 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.01,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Euro-Schatz',
    ticket: 'FGBS',
    ticketMT5: 'DG',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 1060, intradia: 265 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.005,
    valorTick: 5.00,
});
requisitos.push({
    activo: 'Euro-Buxl',
    ticket: 'FGBX',
    ticketMT5: 'FGBX',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 11350, intradia: 2837.50 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.02,
    valorTick: 20.00,
});
requisitos.push({
    activo: 'Long-Term Euro-BTP',
    ticket: 'FBTP',
    ticketMT5: 'FBTP',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 6400, intradia: 1600 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.01,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Short-Term Euro-BTP',
    ticket: 'FBTS',
    ticketMT5: 'FBTS',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 1235, intradia: 308.75 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.01,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Euro-OAT',
    ticket: 'FOAT',
    ticketMT5: 'FOAT',
    market: 'Bonos',
    contract: 'Futuros',
    exchange: 'Eurex',
    margin: { mantenimiento: 5060, intradia: 1265 },
    months: ['H', 'M', 'U', 'Z'],
    medidaTick: 0.01,
    valorTick: 10.00,
});
// Grains
requisitos.push({
    activo: 'Corn',
    ticket: 'ZC',
    ticketMT5: 'ZCE',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 2100, intradia: 2100 },
    months: ['H', 'K', 'N', 'U', 'Z'],
    medidaTick: 1/4,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'Chicago SRW Wheat',
    ticket: 'ZW',
    ticketMT5: 'ZWA',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 3000, intradia: 3000 },
    months: ['H', 'K', 'N', 'U', 'Z'],
    medidaTick: 1/4,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'Soybeans',
    ticket: 'ZS',
    ticketMT5: 'ZSE',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 3300, intradia: 3300 },
    months: ['F', 'H', 'K', 'N', 'Q', 'U', 'X'],
    medidaTick: 1/4,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'Soybean Oil',
    ticket: 'ZL',
    ticketMT5: 'ZLE',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 2700, intradia: 2700 },
    months: ['F', 'H', 'K', 'N', 'Q', 'U', 'V', 'Z'],
    medidaTick: 1/100,
    valorTick: 6.00,
});
requisitos.push({
    activo: 'Soybean Meal',
    ticket: 'ZM',
    ticketMT5: 'ZME',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 2500, intradia: 2500 },
    months: ['F', 'H', 'K', 'N', 'Q', 'U', 'V', 'Z'],
    medidaTick: 0.10,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Oats',
    ticket: 'ZO',
    ticketMT5: 'ZOE',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 1975, intradia: 1975 },
    months: ['H', 'K', 'N', 'U', 'Z'],
    medidaTick: 1/4,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'Rough Rice',
    ticket: 'ZR',
    ticketMT5: 'ZRE',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 1400, intradia: 1400 },
    months: ['F', 'H', 'K', 'N', 'U', 'X'],
    medidaTick: 0.005,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Mini-Corn',
    ticket: 'XC',
    ticketMT5: 'XC',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 420, intradia: 420 },
    months: ['H', 'K', 'N', 'U', 'Z'],
    medidaTick: 1/8,
    valorTick: 1.25,
});
requisitos.push({
    activo: 'Mini-sized Chicago SRW Wheat',
    ticket: 'XW',
    ticketMT5: 'XW',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 600, intradia: 600 },
    months: ['H', 'K', 'N', 'U', 'Z'],
    medidaTick: 1/8,
    valorTick: 1.25,
});
requisitos.push({
    activo: 'Mini Soybean',
    ticket: 'XK',
    ticketMT5: 'XB',
    market: 'Alimentos',
    contract: 'Futuros',
    exchange: 'CBOT/CME',
    margin: { mantenimiento: 660, intradia: 660 },
    months: ['F', 'K', 'K', 'N', 'Q', 'U', 'X'],
    medidaTick: 1/8,
    valorTick: 1.25,
});
// Meats
requisitos.push({
    activo: 'Feeder Cattle',
    ticket: 'GF',
    ticketMT5: 'GF',
    market: 'Carnes',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 2850, intradia: 2850 },
    months: ['F', 'H', 'J', 'Q', 'U', 'V', 'X'],
    medidaTick: 0.00025,
    valorTick: 12.50,
});
requisitos.push({
    activo: 'Lean Hog',
    ticket: 'HE',
    ticketMT5: 'HE',
    market: 'Carnes',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 1750, intradia: 1750 },
    months: ['G', 'J', 'K', 'M', 'N', 'Q', 'V', 'Z'],
    medidaTick: 0.00025,
    valorTick: 10.00,
});
requisitos.push({
    activo: 'Live Cattle',
    ticket: 'LE',
    ticketMT5: 'GLE',
    market: 'Carnes',
    contract: 'Futuros',
    exchange: 'CME',
    margin: { mantenimiento: 1600, intradia: 1600 },
    months: ['G', 'J', 'M', 'Q', 'V', 'Z'],
    medidaTick: 0.00025,
    valorTick: 10.00,
});